export const userActions = {
	SET_USER: 'SET_USER',
	AUTH_USER: 'AUTH_USER',
	DEAUTH_USER: 'DEAUTH_USER'
};

export const restaurantActions = {
	SET_RESTAURANTS: 'SET_RESTAURANTS',
	SET_RESTAURANT_MENU: 'SET_RESTAURANT_MENU'
};

export const orderActions = {
	SET_ORDERS: 'SET_ORDERS',
	UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS'
};

export const cartActions = {
	ADD_CART_ITEM: 'ADD_CART_ITEM',
	REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
	RESET_CART: 'RESET_CART'
}